---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# BASE
name: austereos
description: A bare-chilling-bones OS
base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: latest

# LOCATION
modules:
- type: files
  files:
  - source: system
    destination: /

- type: dnf
  group-install:
    packages:
    - gnome-desktop
    - plasma-desktop

- type: script
  snippets:
    # Safe commands that won't crash the container builder
    - systemctl enable gdm.service
    - systemctl set-default graphical.target

- type: signing
