---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# BASE
name: austereos
description: A bare-chilling-bones OS
base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: latest

# LOCATION
modules:
- type: files
  files:
  - source: system
    destination: /
- type: rpm-ostree
  repos:
  - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-addons-fedora-%OS_VERSION%.repo
  replace:
  - from-repo: https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-fedora-%OS_VERSION%.repo
    packages:
    - kernel
    - kernel-core
    - kernel-modules
    - kernel-modules-core
    - kernel-modules-extra
  install:
  - cachyos-settings
- type: signing
